name: dumper
description: A ridiculously simple build server for Dart web apps served over GitHub Pages.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  async: ^2.4.0
  collection: ^1.14.12
  convert: ^2.1.1
  crypto: ^2.1.3
  markdown: ^2.1.1
  shelf: ^0.7.5
  shelf_router: ^0.7.1
  shelf_static: ^0.2.8

dev_dependencies:
  quantaly_lints:
    git:
      url: https://github.com/Quantaly/dart_lints
